### ISSUE TITLE
[Bug]ClashX 按照模板添加Trojan配置后,UI中不显示Trojan的节点

### ISSUE THREAD

**Issue by GeorgeChen0821** [yichengchen/clashX#250]
### 重现问题的具体布骤 Steps to Reproduce

1. 按照本项目提供的Trojan模板添加Trojan配置
2. Trojan在别的代理软件中可正常连接，翻墙
3. ClashX 能ping到新配置的Trojan的节点(自动选择有时候会选到)
4. 但是列表UI中无法显示：
<img width="410" alt="Screen Shot 2020-03-24 at 1 39 37 AM" src="https://user-images.githubusercontent.com/59362011/77346063-91e9ba00-6d70-11ea-8019-f2c3c49d4925.png">

### clash core config

```
- name: "49HSDtrojan"
  type: trojan
  server: example.xyz
  port: 443
  password: mypasswd
  udp: true
  sni: example.xyz
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true
# url-test 通过指定的 URL 测试并选择延迟最低的节点
- name: "自动节点选择"
  type: url-test
  proxies:
    - "HostDare"
    - "49HSDtrojan"
    - "BWG"
    - "GIGS"
    - "GoogleTrojan"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

# 代理节点选择
- name: "PROXY"
  type: select
  proxies:
    - "自动节点选择"
    - "HostDare"
    - "49HSDtrojan"
    - "BWG"
    - "GIGS"
    - "GoogleTrojan"
……
```

### Clash log

```
……
```
