### ISSUE TITLE
can't modify external-controller port

### ISSUE THREAD

**Issue by win5do** [yichengchen/clashX#312]
change yaml and dashboard bath not work.

```yaml
port: 7890
socks-port: 7891
redir-port: 0
allow-lan: true
mode: Rule
log-level: info
external-controller: '0.0.0.0:7899'
```

![image](https://user-images.githubusercontent.com/22112659/80301354-43e42e00-87d6-11ea-90fb-45e783ff1e4e.png)
