### ISSUE TITLE
ClashX Pro设置增强模式后终端访问不了github或者百度之类的网站

### ISSUE THREAD

**Issue by gmmmn** [yichengchen/clashX#326]
+ version：ClashX Pro 1.19.2.4

设置增强模式后，终端里git提交代码到github失败，curl测试发现百度、github等网站均解析不了，浏览器里没问题，应该是dns被设置成192.168.0.2的原因，上一个版本dns为127.0.0.1的时候没问题

**Comment by yichengchen** [comment]
配置文件里面有tun hijack的相关配置吗？ .4版本开始默认使用hijack dns避免出现某些系统无法在127上监听dns的问题

**Comment by yichengchen** [comment]
提供一下开增强模式前后的log？

**Comment by gmmmn** [comment]
dns及tun配置如下：
```YAML
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
  - 114.114.114.114
  - 223.5.5.5
 enhanced-mode: fake-ip # redir-host
  fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  fake-ip-filter: # fake-ip 白名单列表
  - '*.lan'
  - localhost.ptlogin2.qq.com
  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
    - tls://13800000000.rubyfish.cn:853
    - 119.29.29.29
    - 180.76.76.76
    #- https://13800000000.rubyfish.cn/

  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - tls://13800000000.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

    #- https://13800000000.rubyfish.cn/
    #- https://cloudflare-dns.com/dns-query
    #- https://dns.google/dns-query

  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4

tun:
  enable: true
  stack: gvisor # or system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
```

> log我把日志级别调成debug，然后在终端里`curl https://github.com`或者`curl https://baidu.com`均没有发现相关日志，有什么好的建议吗？非常感谢
