### ISSUE TITLE
最近很忙，提问题是时候最好带上clashx的log~

### ISSUE THREAD

**Issue by yichengchen** [yichengchen/clashX#365]
打不开、设置代理失败的时候 麻烦帮忙看看有没有系统crash log，位于 ~/Library/Logs/DiagnosticReports 或者打开“控制台”在侧边栏找到崩溃报告栏目。看看里面有没有clash相关的报告。

**Comment by qyzxg** [comment]
辛苦了，现在发现的都是些小问题，不影响使用，不忙的时候处理一下就行了

**Comment by danaOng** [comment]
可以在这边提出问题吗

**Comment by fenglangjunzi** [comment]
像如下的这些配置能不能做成全局，在yaml中一更新就没了
```
dns:
  enable: true
  nameserver:
    - 114.114.114.114
```
