### ISSUE TITLE
Clash X pro无法选择 redir-host模式

### ISSUE THREAD

**Issue by iamwwc** [yichengchen/clashX#366]
stack和DNS都是灰色的

![image](https://user-images.githubusercontent.com/24750337/102497629-d9a93200-40b3-11eb-88d4-c1b480252861.png)
![image](https://user-images.githubusercontent.com/24750337/102498771-5a1c6280-40b5-11eb-818c-ba3b6be109ff.png)

部分配置文件如下
```
tun:
  enable: true
  stack: system # or gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  # dns-hijack:
  #   - tcp://8.8.8.8:53
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
```
