### ISSUE TITLE
使用全局代理模式,  git clone还是很慢

### ISSUE THREAD

**Issue by Valar103769** [yichengchen/clashX#407]

**Comment by BenjaminGao** [comment]
git clone 代理很慢跟用不用全局模式无关。解决方式有二种。

## 第一种：给 ssh 开启代理

https://kanda.me/2019/07/01/ssh-over-http-or-socks/

## 第二种：使用 ClashX Pro 开启增强模式

增强模式需要更改配置文件

**Comment by RoyRao2333** [comment]
> git clone 代理很慢跟用不用全局模式无关。解决方式有二种。
> 
> ## 第一种：给 ssh 开启代理
> https://kanda.me/2019/07/01/ssh-over-http-or-socks/
> 
> ## 第二种：使用 ClashX Pro 开启增强模式
> 增强模式需要更改配置文件

请问一下增强模式该怎么修改配置文件呢？

**Comment by liukaiwen0422** [comment]
给hhtp变量加proxy吧

**Comment by BenjaminGao** [comment]
> > git clone 代理很慢跟用不用全局模式无关。解决方式有二种。
> > ## 第一种：给 ssh 开启代理
> > https://kanda.me/2019/07/01/ssh-over-http-or-socks/
> > ## 第二种：使用 ClashX Pro 开启增强模式
> > 增强模式需要更改配置文件
> 
> 请问一下增强模式该怎么修改配置文件呢？

才看见。
在你用的配置中，加入下边的参数就行了。注意 **tun** 和 **dns** 是两个主 **节点**，下边的都是子节点，所以要注意缩进。保存配置文件后关闭 **设置为系统代理**，只打开 **增强模式** 即可。
```yaml
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
    - 8.8.8.8:1053
dns:
  enable: true
  listen: 127.0.0.1:53
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.10.0.1/16
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
```
