### ISSUE TITLE
trojan + grpc 回导致应用crash 直接退出

### ISSUE THREAD

**Issue by Ariesly** [yichengchen/clashX#509]
客户端:

```yaml
proxies:
- type: trojan
  name: trojan-grpc
  server: servername
  port: 443
  password: password
  udp: true
  alpn:
    - h2
  sni: hostname
  skip-cert-verify: false
  network: grpc
  grpc-opts:
    grpc-service-name: "servicename"
```

服务器:  xray + nginx
```json
    {
      "port": 6565,
      "listen": "0.0.0.0",
      "protocol": "trojan",
      "settings": {
        "clients": [{
          "password": "password"
        }]
      },
      "tag": "grpc-in",
      "streamSettings": {
        "network": "grpc",
        "security": "none",
        "grpcSettings": {
          "serviceName": "servicename"
        }
      }
    }
```

**如何复现该错误**
复现步骤:
1. 开启代理
2. 打开YouTube 4k视频
3. 大概率crash并直接退出

**预期行为**
稳定运行

**屏幕截图**
无

**设备信息 (请完成以下信息):**
Macintosh; Intel Mac OS X 11_2_3

**应用信息**
 - 版本: 1.50.01
 - 应用来源: AppCenter

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
```yaml
见上.
```

**日志**
```
直接crash 无日志
```
