### ISSUE TITLE
[Bug] 不支持nameserver-policy，clash最新内核已经支持，clashxpro版本是昨晚的版本

### ISSUE THREAD

**Issue by skill7899** [yichengchen/clashX#584]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [ ✓] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ✓] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ X] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
dns:
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver-policy:
    'www.abc.com':'172.16.31.1'
```

### ClashX log

```
2021/07/05 14:34:00.256  [info] yaml: line 71: did not find expected key
```

### ClashX Crash log

```

```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
MACOS 11.5
* 网路环境或拓扑 (network conditions/topology)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他
针

### 重现问题的具体布骤 Steps to Reproduce

使用 clashX pro 1.65.0.1  clash内核我看已经更新支持 nameserver-policy 在clash 配置不生效，无法启动
建议clahsX pro 更新clash内核也把相应的内核版本也说明一下，不然不知道是否已经更新到最新的版本内核
