### ISSUE TITLE
[Bug] 一些请求会一直pending状态 如: config.js

### ISSUE THREAD

**Issue by Ariesly** [yichengchen/clashX#646]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```yaml
# config.yaml
ipv6: true
external-controller: 127.0.0.1:9090
mixed-port: 7890
redir-port: 7892
experimental:
  ignore-resolve-fail: true

profile:
  store-selected: true
  tracing: false

clash-for-android: 
  ui-subtitle-pattern: "[\u4e00-\u9fa5]{2,4}"
proxy-providers:
  Home:
    type: http
    behavior: classical
    url: 'https://server/path/home.yaml'
    path: ./Path/Home
...

proxies: 
- type: ss
  cipher: aes-128-gcm
  name: backHome
  password: password
  port: 443
  server: server
  udp: false
  plugin: obfs
  plugin-opts:
    mode: tls
    host: cloudfront.net
...
rules:
- RULE-SET,Home,backHome
...



# home.yaml
payload:
- IP-CIDR,10.0.0.0/24,no-resolve
```

### ClashX log

```
2021-09-24 12:02:38[info] [TCP] 127.0.0.1:59256 --> 10.0.0.82:80 match RuleSet(Home) using home[backHome]
2021-09-24 12:02:38[info] [TCP] 127.0.0.1:59256 --> 10.0.0.82:80 match RuleSet(Home) using home[backHome]
2021-09-24 12:02:38[info] [TCP] 127.0.0.1:57093 --> 10.0.0.82:80 match RuleSet(Home) using home[backHome]
2021-09-24 12:02:38[info] [TCP] 127.0.0.1:59382 --> 10.0.0.82:80 match RuleSet(Home) using home[backHome]
```

### ClashX Crash log

```
无Crash
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
Intel Mac OS X 11.6 (20G165)
* 网路环境或拓扑 (network conditions/topology)

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

config.js 这个请求一直失败，导致网页打不开.

### 重现问题的具体布骤 Steps to Reproduce

1. 浏览器请求 http://10.0.0.82
2. 子请求 http://10.0.0.82/web-static/dynaform/class.css 
2. 子请求 http://10.0.0.82/web-static/dynaform/class.js
3. 子请求 http://10.0.0.82/web-static/dynaform/config.js

**我预期会发生……？**
网页打开正常.
并所有请求均正常.

**实际上发生了什麽？**
其他请求正常
只有子请求 http://10.0.0.82/web-static/dynaform/config.js 状态一直pending.
请求失败.

### 可能的解决方案 Possible Solution

config.js 会不会这个config关键字触发了某些规则. 导致丢失

### 更多信息 More Information
ClashForAndroid v2.4.11.premium
使用相同的配置.
能正常打开.
